DROP TABLE IF EXISTS astronauts;
DROP TABLE IF EXISTS agencies;

CREATE TABLE IF NOT EXISTS agencies (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  founded INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS astronauts (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  destination TEXT,
  agency_id INTEGER REFERENCES agencies(id) ON DELETE CASCADE
);